[project]
name = "python-dca"
version = "0.1.0"
description = "Compute DCA ETF deposit equilibrium based on existing investment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pyscipopt",
    "cvxpy"
]
