[project]
name = "ETF-Optmizer"
version = "1.0.1"
description = "Compute DCA ETF deposit equilibrium based on existing investment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pyscipopt",
    "cvxpy",
    "gradio",
    "pandas",
    "matplotlib",
    "pyQt6",
    "yfinance"
]

[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"